# Generated by Django 5.1.2 on 2024-11-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('sellerID', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('createdAtProduct', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('createdAt', models.DateField()),
            ],
        ),
    ]
