# Generated by Django 5.1.2 on 2024-10-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.IntegerField()),
                ('title', models.CharField(max_length=2010)),
                ('sellerId', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
    ]
