# Generated by Django 5.1.2 on 2024-11-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='idnum',
            new_name='productID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_num',
            new_name='userID',
        ),
    ]
