# Generated by Django 5.1.2 on 2024-11-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_idnum_product_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.IntegerField(),
        ),
    ]
