# Generated by Django 5.1.2 on 2024-11-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_sellerid_old_alter_product_sellerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sellerID_old',
        ),
    ]
