# Generated by Django 5.1.2 on 2024-11-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_sellerid_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('under_negotiation', 'Under Negotiation')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
