# Generated by Django 5.1.2 on 2024-11-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdAt',
            field=models.CharField(max_length=2010),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
