# Generated by Django 5.1.2 on 2024-11-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_createdat_alter_user_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createdAt',
            new_name='createdAtProduct',
        ),
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DateField(),
        ),
    ]
