# Generated by Django 5.1.2 on 2024-11-05 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_status_alter_product_sellerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sellerID',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productID',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=10),
        ),
    ]
