# Generated by Django 5.1.2 on 2024-11-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_createdat_product_createdatproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sellerId',
            new_name='sellerID',
        ),
    ]
