# Generated by Django 5.1.2 on 2024-11-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_product_status_product_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='sellerID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
